const PRICE_SORT = 'PRICE_SORT';
const POPULARITY_SORT = 'POPULARITY_SORT';
const SET_SHOP_PRODUCTS = 'SET_SHOP_PRODUCTS';
const PRICE_FILTER = 'PRICE_FILTER';
const SHOP_PRODUCTS_LOADING = 'SHOP_PRODUCTS_LOADING';

export { PRICE_SORT, POPULARITY_SORT, SET_SHOP_PRODUCTS, SHOP_PRODUCTS_LOADING, PRICE_FILTER };